const chromium = require('@sparticuz/chromium');
const puppeteer = require('puppeteer-core');

export default async function handler(req, res) {
  // Hanya izinkan POST request dari n8n
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Gunakan metode POST' });
  }

  try {
    const { name, date, items } = req.body;

    const browser = await puppeteer.launch({
      args: chromium.args,
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
    });

    const page = await browser.newPage();

    // Template HTML yang lebih rapi
    const htmlContent = `
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
          .invoice-box { max-width: 800px; margin: auto; border: 1px solid #eee; padding: 30px; }
          .title { font-size: 24px; font-weight: bold; color: #007bff; margin-bottom: 10px; }
          table { width: 100%; text-align: left; border-collapse: collapse; margin-top: 20px; }
          th { background: #f8f9fa; padding: 10px; border-bottom: 2px solid #eee; }
          td { padding: 10px; border-bottom: 1px solid #eee; }
          .total { font-weight: bold; text-align: right; margin-top: 20px; }
        </style>
      </head>
      <body>
        <div class="invoice-box">
          <div class="title">INVOICE DIGITAL</div>
          <p><strong>Customer:</strong> ${name || 'Pelanggan'}</p>
          <p><strong>Tanggal:</strong> ${date || new Date().toLocaleDateString('id-ID')}</p>
          <table>
            <thead>
              <tr><th>Item</th><th>Harga</th></tr>
            </thead>
            <tbody>
              ${items ? items.map(i => `<tr><td>${i.name}</td><td>${i.price}</td></tr>`).join('') : '<tr><td>Layanan Custom</td><td>-</td></tr>'}
            </tbody>
          </table>
          <div class="total">Generated by n8n + Vercel</div>
        </div>
      </body>
    </html>`;

    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
    
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '1cm', right: '1cm', bottom: '1cm', left: '1cm' }
    });

    await browser.close();

    // Kirim sebagai binary PDF
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=hasil_generate.pdf');
    return res.status(200).send(pdf);

  } catch (error) {
    return res.status(500).json({ error: 'Gagal generate PDF', details: error.message });
  }
}
